project:
  type: website
  output-dir: _site

date: last-modified
date-format: D MMMM, YYYY

website:
  title: "White Rose Analytics 1: Reproducibility with R"
  # google-analytics: "G-TVF95J593T"
  
  page-footer:
    left: "Rand E (2025). White Rose Analytics 1: Reproducibility with R. <https://3mmarand.github.io/wr-analytics-1/>."
    right:
      - icon: github
        href: https://github.com/3mmaRand/wr-analytics-1
        text: "Emma on GitHub"  
  navbar:
    background: light
    twitter-card: true
    site-url: https://3mmarand.github.io/wr-analytics-1/
    repo-url: https://github.com/3mmaRand/wr-analytics-1
    issue-url: https://github.com/3mmaRand/wr-analytics-1/issues/new/choose
    repo-actions: [edit, issue]
    page-navigation: true
    search: true
    left:
      - text: "Welcome!"
        file: index.qmd
      - text: "Prerequisites"
        file:  prerequisites.qmd
      - text: "Schedule and materials"
        file:  schedule.qmd
    tools:
    right:
      - icon: github
        href: https://github.com/3mmaRand/wr-analytics-1
        text: "Emma on GitHub"

execute:
  echo: true
  warning: false
  output: true
  error: true
  collapse: true
  freeze: auto

engine: knitr

format:
  html:
    css: styles.css
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/3mmarand\.github\.io\/wr-analytics-1-data'
    theme:
      light: [cosmo, custom.scss]
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-line-numbers: false
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    
    author-meta: Emma Rand

metadata-files:
  - _downlit.yml

fig-dpi: 600

bibliography: references.bib

editor: source